### ISSUE TITLE
question about dataset

### ISSUE THREAD

**Issue by wjczf123** [zyh190507/KnnContrastiveForOOD#1]
Hi, yunhua.

I see that you write ''After datasets are split into train, validation, and test respectively, we randomly sample 25%, 50%, and 75% of the intent classes and discard the remaining classes in the training and validation sets.'' in your paper.
I can see that BANKING and stackoverflow dataset do not have OOD class in validation.

For CLINC-FULL and CLINC-SMALL dataset, do their validation set have OOD class?

**Comment by zyh190507** [comment]
hi, we extracted OOD from the validation set of CLINC in advance. THX.

**Comment by wjczf123** [comment]
Thanks. I get it.
