### ISSUE TITLE
ValueError: Sample larger than population or is negative

### ISSUE THREAD

**Issue by sunsunshinesunshine** [zyh190507/KnnContrastiveForOOD#2]
Thanks for releasing your code. I use another dataset to run your code. I met this error: 

trainer.py", line 289, in generate_positive_sample
positive_sample.extend(random.sample(self.negative_data[input_label], positive_num)
raise ValueError("Sample larger than population or is negative")

Can i modify positive_num to one? In your paper,  default positive_num is three.  Does this modification have a big impact on the results? Looking forward to your reply.

**Comment by zyh190507** [comment]
Hi, thank you for paying attention to our work.
1) I thought about your ValueError. I'm sorry I have no idea for the moment (The code is a little long away). I have never encountered such a situation, and I can help you think about it later.
2) I haven't tried to make positive_num to 1 before. But I try other values (you can refer to the analysis), it will have an impact. After all, we don't know the best k.

**Comment by sunsunshinesunshine** [comment]
Thanks for your reply. Maybe I didn't make it clear. I read your code in your model.py . 
The positive_num you use in your code is self.update_num = config.positive_num.
I think is not the K in your paper. Can I change the update_num from three to one? You default update_num  is three.

**Comment by zyh190507** [comment]
hi,  I just checked it roughly. It seems that I didn't make specific restrictions (maybe I forget some specific details). I had never encountered such a problem before, so I didn't pay attention to it. I will think later.

**Comment by zyh190507** [comment]
hi, We also used another new dataset (MCID or extract 25% from clinc) for verification today, but we didn't encounter the problem you mentioned. <img width="724" alt="image" src="https://user-images.githubusercontent.com/19834275/203989753-42a7fa80-4074-46d5-9336-b0b12cdf3686.png">

**Comment by zyh190507** [comment]
hi, We also used another new dataset (MCID or extract 25% from clinc) for verification today, but we didn't encounter the problem you mentioned.<img width="488" alt="image" src="https://user-images.githubusercontent.com/19834275/203990304-cad344ff-b4c5-4098-916e-4ff785dec314.png">

**Comment by sunsunshinesunshine** [comment]
Thanks for your reply. I find that the number of training examples of some classes in the dataset I used is only 1 or 2. I would like to ask if this is the cause of the problem.

**Comment by zyh190507** [comment]
I have tested on new datasets many times before and haven't encountered it. I can't think of any reason for this....

**Comment by sunsunshinesunshine** [comment]
Thank you very much for your patient reply!
