### ISSUE TITLE
Is the result much worse because of a missing parameter file?

### ISSUE THREAD

**Issue by JianhuaSu** [zyh190507/KnnContrastiveForOOD#3]
After running, I found that there was a big difference between the results I ran and those provided by the author. Is it because of the lack of these two corresponding hyperparameter files?

    sim_embed: str = field(default="/remote-home/dmsong/train_data/adv_learn/counter-fitted-vectors.txt")
    cosine_npy: str = field(default="/remote-home/dmsong/train_data/adv_learn/cos_sim_counter_fitting.npy")

**Comment by zyh190507** [comment]
Hi, thank you for your attention to our work. Our model does not use these two parameters files. Please check the process of your implementation and the parameters for different datasets (Ours in .json files). We have replicated our model many times, and many other people have also repeated our model. The results are not significantly different. Best wishes.

**Comment by JianhuaSu** [comment]
Thank you,I'll try again.

**Comment by JianhuaSu** [comment]
I would like to ask the paper said that there are 3 seed numbers, but only two were found in the code. What is the other one?

**Comment by zyh190507** [comment]
The paper actually says that take different random seeds to run 3 rounds, and you can try 52 or randomly assign seeds.

**Comment by JianhuaSu** [comment]
Thank you

**Comment by JianhuaSu** [comment]
![image](https://user-images.githubusercontent.com/74132552/221813024-cb21a5cd-923a-4854-b195-97461ad3c8f7.png)
I would like to ask what the parameters of this result are? Are you following a json file or modifying any parameters? I couldn't have gotten away with this.

**Comment by zyh190507** [comment]
The result is obtained just using the provided json file. We conducted this experiment to ensure the correctness of our code before uploading it.

**Comment by JianhuaSu** [comment]
ok
